### ISSUE TITLE
Include CMT packaging directory

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/pyomicron#4]
Florent has asked for the ability to package this with CMT, or at least to provide an empty `CMT` directory so that they can work up packaging over at Virgo.

**Comment by duncanmmacleod** [comment]
@FlorentRobinet, can you comment on what exactly is needed for CMT packaging to work?

**Comment by FlorentRobinet** [comment]
You know what, don't worry about that request. I think I will use the standard trick for external packages (root, gsl, fftw, lalsuite...). I will prepare a separate CMT wrapper package pointing to the pyomicron installation.

**Comment by duncanmmacleod** [comment]
thanks @FlorentRobinet, let me know if there is anything I can do to make it easier in this package.
